[plugin-info]
SHORT_PLUGIN_NAME = 'princeton_instruments'

package-url = 'https://github.com/LMSC-NTappy/pymodaq_plugins_princeton_instruments/'
description = 'Control for hyperspy of scientific cameras using the picam library'

author = 'Nicolas Tappy'
author-email = 'nicolas.tappy@epfl.ch'
license = 'MIT'

[plugin-install]
packages-required = ['pylablib']
